name: build-linux

on:
  push:
    branches:
      - "main"

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test
